kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: airbyte-replication-operator-platform
featureGates:
  APIPriorityAndFairness: false
networking:
  apiServerAddress: 192.168.86.123
  apiServerPort: 6443
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            max-requests-inflight: "1000"
            max-mutating-requests-inflight: "1000"
    kubeadmConfigPatchesJSON6902:
      - group: kubeadm.k8s.io
        version: v1beta3
        kind: ClusterConfiguration
        patch: |
          - op: add
            path: /apiServer/certSANs/-
            value: kubernetes.vela.internal
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        listenAddress: 0.0.0.0
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        listenAddress: 0.0.0.0
        protocol: TCP
      - containerPort: 30000
        hostPort: 30000
        listenAddress: 0.0.0.0
        protocol: TCP
      - containerPort: 30001
        hostPort: 30001
        listenAddress: 0.0.0.0
        protocol: TCP
      - containerPort: 30002
        hostPort: 30002
        listenAddress: 0.0.0.0
        protocol: TCP
      - containerPort: 30003
        hostPort: 30003
        listenAddress: 0.0.0.0
        protocol: TCP
      - containerPort: 30004
        hostPort: 30004
        listenAddress: 0.0.0.0
        protocol: TCP
      - containerPort: 30005
        hostPort: 30005
        listenAddress: 0.0.0.0
        protocol: TCP
      - containerPort: 30006
        hostPort: 30006
        listenAddress: 0.0.0.0
        protocol: TCP
      - containerPort: 30007
        hostPort: 30007
        listenAddress: 0.0.0.0
        protocol: TCP
      - containerPort: 30008
        hostPort: 30008
        listenAddress: 0.0.0.0
        protocol: TCP
      - containerPort: 30009
        hostPort: 30009
        listenAddress: 0.0.0.0
        protocol: TCP
      - containerPort: 30010
        hostPort: 30010
        listenAddress: 0.0.0.0
        protocol: TCP
