[package]
name = "e2e"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0.54.1"
aws-sdk-s3 = "0.24.0"
aws-smithy-http = "0.54.1"
local-ip-address = "0.5.1"
parquet = "34.0.0"
polars = { version = "0.27.2", features = ["parquet", "lazy"] }
tokio = "1"
trauma = "2"
